"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { PageHeader } from "@/components/page-header";
import { StatusBadge, statusTone } from "@/components/status-badge";
import { ActionButton, EmptyState, MetricCard, SelectInput, TextInput } from "@/components/ui";

type Invoice = { id:string; document_number:string; source:string; customer_name:string; customer_email:string|null; customer_rtn:string|null; unit_label:string|null; currency:"USD"|"HNL"; subtotal:string; tax:string; total:string; amount_paid:string; credited_amount:string; status:string; cai:string|null; fiscal_correlative:number|null; sent_at:string|null; created_at:string; subtotal_usd:string; tax_usd:string; total_usd:string };
type Payment = { id:string; document_id:string; amount:string; method:string; reference:string|null; paid_at:string; document_number:string; customer_name:string; currency:"USD"|"HNL"; amount_usd:string };
type Range = { id:string; cai:string; range_start:number; range_end:number; current_number:number; expiration_date:string; status:string; document_type:string; establishment:string; emission_point:string; available:number; used:number };
type CreditNote = { id:string; credit_note_number:string; invoice_number:string; customer_name:string; currency:"USD"|"HNL"; total:string; status:string; created_at:string };
type Tab = "Resumen"|"Facturas"|"Pagos"|"CAI / Correlativos"|"Notas de crédito";

const money = (value:number,currency="USD") => new Intl.NumberFormat(currency==="HNL"?"es-HN":"en-US",{style:"currency",currency}).format(value||0);
const todayIso = () => new Date().toISOString().slice(0,10);
const monthStart = () => `${todayIso().slice(0,7)}-01`;
const download = (filename:string, content:string, type:string) => { const blob=new Blob([content],{type}); const url=URL.createObjectURL(blob); const link=document.createElement("a"); link.href=url; link.download=filename; link.click(); URL.revokeObjectURL(url); };
const csvCell = (value:unknown) => `"${String(value??"").replaceAll('"','""')}"`;

export default function ReportesPage(){
  const [invoices,setInvoices]=useState<Invoice[]>([]); const [payments,setPayments]=useState<Payment[]>([]); const [ranges,setRanges]=useState<Range[]>([]); const [creditNotes,setCreditNotes]=useState<CreditNote[]>([]);
  const [tab,setTab]=useState<Tab>("Resumen"); const [from,setFrom]=useState(monthStart); const [to,setTo]=useState(todayIso); const [search,setSearch]=useState(""); const [status,setStatus]=useState("ALL"); const [source,setSource]=useState("ALL"); const [error,setError]=useState("");
  const load=useCallback(async()=>{const response=await fetch("/api/operations",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.message);setInvoices(data.invoices??[]);setPayments(data.payments??[]);setRanges(data.ranges??[]);setCreditNotes(data.creditNotes??[]);},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load().catch((failure)=>setError(failure instanceof Error?failure.message:"No se pudieron cargar los reportes.")),0);return()=>window.clearTimeout(timer);},[load]);
  const inPeriod=useCallback((value:string)=>value.slice(0,10)>=from&&value.slice(0,10)<=to,[from,to]);
  const filtered=useMemo(()=>invoices.filter((invoice)=>inPeriod(invoice.created_at)&&(`${invoice.document_number} ${invoice.customer_name} ${invoice.customer_rtn??""} ${invoice.unit_label??""}`).toLowerCase().includes(search.toLowerCase())&&(status==="ALL"||invoice.status===status)&&(source==="ALL"||invoice.source===source)),[inPeriod,invoices,search,source,status]);
  const filteredPayments=useMemo(()=>payments.filter((payment)=>inPeriod(payment.paid_at)&&(`${payment.document_number} ${payment.customer_name} ${payment.reference??""}`).toLowerCase().includes(search.toLowerCase())),[inPeriod,payments,search]);
  const filteredNotes=useMemo(()=>creditNotes.filter((note)=>inPeriod(note.created_at)&&(`${note.credit_note_number} ${note.invoice_number} ${note.customer_name}`).toLowerCase().includes(search.toLowerCase())),[creditNotes,inPeriod,search]);
  const metrics=useMemo(()=>({subtotal:filtered.filter(i=>i.status!=="CANCELLED").reduce((s,i)=>s+Number(i.subtotal_usd),0),tax:filtered.filter(i=>i.status!=="CANCELLED").reduce((s,i)=>s+Number(i.tax_usd),0),total:filtered.filter(i=>i.status!=="CANCELLED").reduce((s,i)=>s+Number(i.total_usd),0),invoices:filtered.length,cancelled:filtered.filter(i=>i.status==="CANCELLED").length,paid:filteredPayments.reduce((s,p)=>s+Number(p.amount_usd),0),sent:filtered.filter(i=>i.sent_at).length,notes:filteredNotes.filter(n=>n.status!=="CANCELLED").length}),[filtered,filteredNotes,filteredPayments]);
  const activeInvoiceRange=ranges.find(r=>r.status==="ACTIVE"&&r.document_type==="01");
  const exportCsv=()=>{const rows=[["Factura","Fecha","Cliente","RTN","Origen","Moneda","Subtotal","ISV","Total","Pagado","Acreditado","Estado","CAI"],...filtered.map(i=>[i.document_number,i.created_at.slice(0,10),i.customer_name,i.customer_rtn??"",i.source,i.currency,i.subtotal,i.tax,i.total,i.amount_paid,i.credited_amount,i.status,i.cai??""])];download(`reporte-fiscal-${from}-${to}.csv`,rows.map(r=>r.map(csvCell).join(",")).join("\n"),"text/csv;charset=utf-8");};
  return <><PageHeader title="Reportes" description="Reportes fiscales y operativos sincronizados con facturas, pagos, CAI, correlativos y notas de crédito." actions={<><ActionButton variant="secondary" onClick={exportCsv}>Exportar CSV</ActionButton><ActionButton onClick={()=>window.print()}>Imprimir / PDF</ActionButton></>}/><div className="space-y-5 p-5">
    {error?<div className="rounded-lg bg-rose-50 p-3 text-sm font-bold text-rose-700">{error}</div>:null}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="Total facturado" value={money(metrics.total)} hint="Equivalente USD"/><MetricCard label="Base gravada" value={money(metrics.subtotal)} hint="Sin ISV"/><MetricCard label="ISV facturado" value={money(metrics.tax)} hint="Equivalente USD"/><MetricCard label="Pagos registrados" value={money(metrics.paid)} hint="Transferencia y POS"/><MetricCard label="Facturas" value={String(metrics.invoices)} hint={`${metrics.cancelled} anulada(s)`}/><MetricCard label="Correos enviados" value={String(metrics.sent)} hint="Envíos registrados"/><MetricCard label="Notas de crédito" value={String(metrics.notes)} hint="Vigentes en el período"/><MetricCard label="Correlativos disponibles" value={String(activeInvoiceRange?.available??0)} hint={activeInvoiceRange?.cai??"Sin CAI activo"}/></div>
    <section className="no-print grid gap-3 rounded-lg border bg-white p-4 md:grid-cols-3 xl:grid-cols-6"><TextInput type="date" value={from} onChange={e=>setFrom(e.target.value)}/><TextInput type="date" value={to} onChange={e=>setTo(e.target.value)}/><TextInput placeholder="Factura, cliente, RTN o bodega" value={search} onChange={e=>setSearch(e.target.value)}/><SelectInput value={source} onChange={e=>setSource(e.target.value)}><option value="ALL">Todos los orígenes</option><option value="CASH">Caja</option><option value="SERVICE">Servicios</option><option value="PROFORMA">Proforma convertida</option></SelectInput><SelectInput value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">Todos los estados</option><option value="PENDING_PAYMENT">Pendiente</option><option value="PARTIALLY_PAID">Abonada</option><option value="PAID">Pagada</option><option value="CANCELLED">Anulada</option><option value="CREDITED">Acreditada</option></SelectInput><ActionButton variant="secondary" onClick={()=>{setFrom(monthStart());setTo(todayIso());setSearch("");setSource("ALL");setStatus("ALL");}}>Restablecer</ActionButton></section>
    <div className="no-print flex flex-wrap gap-2">{(["Resumen","Facturas","Pagos","CAI / Correlativos","Notas de crédito"] as Tab[]).map(item=><button key={item} onClick={()=>setTab(item)} className={`rounded-md px-4 py-2 text-sm font-black ${tab===item?"bg-[#004B13] text-white":"border bg-white text-slate-700"}`}>{item}</button>)}</div>
    {tab==="Resumen"?<section className="rounded-lg border bg-white p-5"><h2 className="font-black">Resumen fiscal del período</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><p>Período: <strong>{from} al {to}</strong></p><p>CAI factura activo: <strong>{activeInvoiceRange?.cai??"No configurado"}</strong></p><p>Próximo correlativo: <strong>{activeInvoiceRange?`${activeInvoiceRange.establishment}-${activeInvoiceRange.emission_point}-01-${String(activeInvoiceRange.current_number).padStart(8,"0")}`:"-"}</strong></p><p>Facturación neta: <strong>{money(metrics.total)}</strong></p></div><p className="mt-4 rounded-md bg-amber-50 p-3 text-xs font-bold text-amber-800">BAC y Storeganise todavía no están conectados; este reporte no inventa operaciones de esas integraciones.</p></section>:null}
    {tab==="Facturas"?<DataTable empty="No hay facturas en este período." headers={["Número","Fecha","Cliente","Origen","Subtotal","ISV","Total","Estado","PDF"]} rows={filtered.map(i=>[i.document_number,new Date(i.created_at).toLocaleDateString("es-HN"),i.customer_name,i.source,money(Number(i.subtotal),i.currency),money(Number(i.tax),i.currency),money(Number(i.total),i.currency),i.status,<a key={i.id} href={`/api/billing/${i.id}/pdf`} target="_blank" className="font-black text-emerald-800">Abrir</a>])}/>:null}
    {tab==="Pagos"?<DataTable empty="No hay pagos registrados en este período." headers={["Factura","Fecha","Cliente","Método","Referencia","Monto"]} rows={filteredPayments.map(p=>[p.document_number,new Date(p.paid_at).toLocaleDateString("es-HN"),p.customer_name,p.method,p.reference??"-",money(Number(p.amount),p.currency)])}/>:null}
    {tab==="CAI / Correlativos"?<DataTable empty="No hay rangos CAI." headers={["Documento","CAI","Rango","Próximo","Usados","Disponibles","Vence","Estado"]} rows={ranges.map(r=>[r.document_type==="03"?"Nota de crédito":"Factura",r.cai,`${r.range_start}–${r.range_end}`,r.current_number,r.used,r.available,r.expiration_date,<StatusBadge key={r.id} tone={statusTone(r.status)}>{r.status}</StatusBadge>])}/>:null}
    {tab==="Notas de crédito"?<DataTable empty="No hay notas de crédito en este período." headers={["Número","Factura","Fecha","Cliente","Total","Estado"]} rows={filteredNotes.map(n=>[n.credit_note_number,n.invoice_number,new Date(n.created_at).toLocaleDateString("es-HN"),n.customer_name,money(Number(n.total),n.currency),n.status])}/>:null}
  </div></>;
}

function DataTable({headers,rows,empty}:{headers:string[];rows:React.ReactNode[][];empty:string}){return <section className="rounded-lg border bg-white">{!rows.length?<div className="p-4"><EmptyState text={empty}/></div>:<div className="overflow-x-auto"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{row.map((cell,cellIndex)=><td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div>}</section>}
